"""The numbers a dragged piece is judged by, written out for the browser.

    python -m standardphysics_agents.fix.geometry_rules > apps/web/src/types/geometry-rules.ts

A piece dragged in the workspace slides along whatever it would run into, so
the browser tests every step against the footprints, tolerances and limits the
hard constraints hold a layout to. It used to keep its own copies of those
numbers, typed in by hand. Each one is now read from the module that defines
it and written into one TypeScript module, beside the contract types: `npm run
contracts` in apps/web regenerates both, and CI fails when either differs from
the committed copy. The server still checks every layout the browser lets
through.
"""

from __future__ import annotations

import ast
import inspect
import json
import sys
import textwrap
from dataclasses import dataclass
from types import ModuleType

from standardphysics_contracts import geometry, scene
from standardphysics_pipeline import occupancy

from . import constraints, moves

BANNER = """/**
 * Generated by `npm run contracts` from the Python constant each value names. Do not edit.
 * Change the constant where it is defined, then regenerate.
 */
"""

COMMENT_WIDTH = 100


@dataclass(frozen=True)
class Shared:
    """One constant the browser uses, and the module that defines it."""

    module: ModuleType
    name: str

    @property
    def value(self) -> object:
        return getattr(self.module, self.name)

    @property
    def source(self) -> str:
        return f"{self.module.__name__}.{self.name}"


SHARED = tuple(
    Shared(module, name)
    for module, names in (
        (geometry, ("METERS_PER_INCH",)),
        (scene, ("SHEET_THICKNESS", "SHEET_AREA", "SHEET_REACH")),
        (occupancy, ("BLOCKING_HEIGHT", "CANE_DETECTABLE", "UNCLAIMED_SURFACE", "PASSABLE_KINDS")),
        (moves, ("RESTING_GAP", "RIDING_GAP", "HAND_CARRIED_VOLUME", "HAND_CARRIED_HEIGHT", "HAND_CARRIED_SPAN")),
        (constraints, (
            "FLOOR_MARGIN", "OVERLAP_TOLERANCE", "VERTICAL_TOLERANCE", "HOME_METERS", "MAX_TRAVEL_METERS",
            "SWING_KINDS", "DOOR_SWEEP_ALONG", "DOOR_SWEEP_ACROSS",
        )),
    )
    for name in names
)


def _assigned_name(statement: ast.stmt) -> str | None:
    if isinstance(statement, ast.Assign) and len(statement.targets) == 1 and isinstance(statement.targets[0], ast.Name):
        return statement.targets[0].id
    if isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name):
        return statement.target.id
    return None


def _string_literal(statement: ast.stmt) -> str | None:
    if isinstance(statement, ast.Expr) and isinstance(statement.value, ast.Constant):
        return statement.value.value if isinstance(statement.value.value, str) else None
    return None


def _follows(statement: ast.stmt, previous: ast.stmt | None) -> bool:
    return previous is not None and statement.lineno == (previous.end_lineno or previous.lineno) + 1


def attribute_docs(module: ModuleType) -> dict[str, str]:
    """Each module-level constant's docstring, the string written on the line under it.

    A docstring under a run of assignments on consecutive lines, like the one
    under `HAND_CARRIED_HEIGHT` and `HAND_CARRIED_SPAN`, describes the whole run.
    """
    docs: dict[str, str] = {}
    run: list[str] = []
    previous: ast.stmt | None = None
    for statement in ast.parse(inspect.getsource(module)).body:
        name, text = _assigned_name(statement), _string_literal(statement)
        joined = _follows(statement, previous)
        if name is not None:
            run = [*run, name] if joined else [name]
        elif text is not None and joined:
            docs.update(dict.fromkeys(run, text))
            run = []
        else:
            run = []
        previous = statement
    return docs


def _summary(docstring: str | None) -> str | None:
    if not docstring:
        return None
    return " ".join(inspect.cleandoc(docstring).split("\n\n")[0].split())


def _comment(lines: list[str]) -> str:
    wrapped = [textwrap.fill(line, COMMENT_WIDTH - 3) if line else "" for line in lines]
    body = "\n".join(f" * {line}".rstrip() for text in wrapped for line in text.split("\n"))
    return f"/**\n{body}\n */"


def _declaration(name: str, value: object) -> str:
    """The TypeScript for one constant: a number, a string, or a set of strings looked up by membership."""
    if isinstance(value, bool) or not isinstance(value, int | float | str | frozenset | set):
        raise TypeError(f"{name} is a {type(value).__name__}, which the browser has no literal for")
    if isinstance(value, frozenset | set):
        members = ", ".join(json.dumps(member) for member in sorted(value))
        return f"export const {name}: ReadonlySet<string> = new Set([{members}]);"
    literal = json.dumps(value) if isinstance(value, str) else repr(value)
    return f"export const {name} = {literal};"


def typescript() -> str:
    """The whole generated module, as `npm run contracts` writes it."""
    docs = {module: attribute_docs(module) for module in {shared.module for shared in SHARED}}
    blocks = [BANNER]
    for shared in SHARED:
        summary = _summary(docs[shared.module].get(shared.name))
        lines = [summary, "", f"From `{shared.source}`."] if summary else [f"From `{shared.source}`."]
        blocks.append(f"{_comment(lines)}\n{_declaration(shared.name, shared.value)}\n")
    return "\n".join(blocks)


if __name__ == "__main__":
    sys.stdout.write(typescript())
