/**
 * Generated by `npm run contracts` from the Python constant each value names. Do not edit.
 * Change the constant where it is defined, then regenerate.
 */

/**
 * From `standardphysics_contracts.geometry.METERS_PER_INCH`.
 */
export const METERS_PER_INCH = 0.0254;

/**
 * How thin a region has to be to read as a sheet rather than a solid, in metres.
 *
 * From `standardphysics_contracts.scene.SHEET_THICKNESS`.
 */
export const SHEET_THICKNESS = 0.05;

/**
 * And how broad, in square metres, so that a shelf board is not a wall.
 *
 * From `standardphysics_contracts.scene.SHEET_AREA`.
 */
export const SHEET_AREA = 1.0;

/**
 * Or how far its long side runs, in metres, so a narrow wall return beside a column still reads as
 * the room. The Share Tea scan has two, 15 and 27 cm wide and 3 m tall, well under a square metre
 * and nothing like a shelf board.
 *
 * From `standardphysics_contracts.scene.SHEET_REACH`.
 */
export const SHEET_REACH = 2.0;

/**
 * A node blocks the floor when its top rises above 1/4 inch.
 *
 * From `standardphysics_pipeline.occupancy.BLOCKING_HEIGHT`.
 */
export const BLOCKING_HEIGHT = 0.00635;

/**
 * Height below which an object counts as being in the way.
 *
 * From `standardphysics_pipeline.occupancy.CANE_DETECTABLE`.
 */
export const CANE_DETECTABLE = 0.6858;

/**
 * The category of a box drawn around scanned faces nothing has claimed. It bounds a surface, which
 * can run along a whole wall and ceiling, so it says where something was seen, not how much floor
 * anything takes up.
 *
 * From `standardphysics_pipeline.occupancy.UNCLAIMED_SURFACE`.
 */
export const UNCLAIMED_SURFACE = "lidar_candidate";

/**
 * Doors and openings are how you get through a wall, not obstacles.
 *
 * From `standardphysics_pipeline.occupancy.PASSABLE_KINDS`.
 */
export const PASSABLE_KINDS: ReadonlySet<string> = new Set(["door", "floor", "opening", "window"]);

/**
 * A piece whose underside is more than this above the floor was resting on something.
 *
 * From `standardphysics_agents.fix.moves.RESTING_GAP`.
 */
export const RESTING_GAP = 0.12;

/**
 * A piece whose underside is within this of another's top is sitting on it.
 *
 * From `standardphysics_agents.fix.moves.RIDING_GAP`.
 */
export const RIDING_GAP = 0.05;

/**
 * Cubic metres of bounding box one person carries: a sign stand, a stanchion, a bin, a stool or a
 * high chair, and not a display case or a booth.
 *
 * From `standardphysics_agents.fix.moves.HAND_CARRIED_VOLUME`.
 */
export const HAND_CARRIED_VOLUME = 0.3;

/**
 * Metres. Taller or longer than this and a piece is walked, not carried.
 *
 * From `standardphysics_agents.fix.moves.HAND_CARRIED_HEIGHT`.
 */
export const HAND_CARRIED_HEIGHT = 1.3;

/**
 * Metres. Taller or longer than this and a piece is walked, not carried.
 *
 * From `standardphysics_agents.fix.moves.HAND_CARRIED_SPAN`.
 */
export const HAND_CARRIED_SPAN = 0.9;

/**
 * A centimetre of slack at the floor edge, for arithmetic rather than for room.
 *
 * From `standardphysics_agents.fix.constraints.FLOOR_MARGIN`.
 */
export const FLOOR_MARGIN = 0.01;

/**
 * How far two things may interpenetrate before it counts as a collision.
 *
 * From `standardphysics_agents.fix.constraints.OVERLAP_TOLERANCE`.
 */
export const OVERLAP_TOLERANCE = 0.005;

/**
 * How far a piece may sink into the one under it and still count as resting on it.
 *
 * From `standardphysics_agents.fix.constraints.VERTICAL_TOLERANCE`.
 */
export const VERTICAL_TOLERANCE = 0.02;

/**
 * How near where the scan found it a piece counts as not moved.
 *
 * From `standardphysics_agents.fix.constraints.HOME_METERS`.
 */
export const HOME_METERS = 0.01;

/**
 * How far a piece may end up from where the scan found it: 60 inches.
 *
 * From `standardphysics_agents.fix.constraints.MAX_TRAVEL_METERS`.
 */
export const MAX_TRAVEL_METERS = 1.524;

/**
 * From `standardphysics_agents.fix.constraints.SWING_KINDS`.
 */
export const SWING_KINDS: ReadonlySet<string> = new Set(["door"]);

/**
 * How far a door's keep-clear square runs along its wall each side of the door's centre, in opening
 * widths.
 *
 * From `standardphysics_agents.fix.constraints.DOOR_SWEEP_ALONG`.
 */
export const DOOR_SWEEP_ALONG = 0.5;

/**
 * How far the square reaches out from the wall on each side, in opening widths: a leaf is as long
 * as its opening.
 *
 * From `standardphysics_agents.fix.constraints.DOOR_SWEEP_ACROSS`.
 */
export const DOOR_SWEEP_ACROSS = 1.0;
