"""Typed inputs and results for the bounded accessibility judgments."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field
from standardphysics_contracts import Finding

from .accessibility_vocabulary import GoalKind, ReviewRoute
from .ask.query import QueryKind


@dataclass(frozen=True)
class ChoiceJudgment:
    value: str
    probabilities: dict[str, float]
    confidence: float


@dataclass(frozen=True)
class ScoreJudgment:
    value: float
    probabilities: dict[str, float]
    confidence: float


@dataclass(frozen=True)
class MeasurementRoute:
    kind: QueryKind
    executor: Callable
    judgment: ChoiceJudgment


class LayoutCandidate(BaseModel):
    """Metrics computed by layout code, not claims generated by Jev."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=100)
    deterministic_checks_passed: Literal[True]
    usability_evidence: dict
    disruption_evidence: dict


@dataclass(frozen=True)
class RankedLayout:
    candidate: LayoutCandidate
    usability: ScoreJudgment
    disruption: ScoreJudgment
    composite: float


@dataclass(frozen=True)
class PrioritizedFinding:
    finding: Finding
    customer_impact: ScoreJudgment


@dataclass(frozen=True)
class EvidenceAudit:
    contradiction_probability: float
    missing_evidence_probability: float

    @property
    def needs_review(self) -> bool:
        return max(
            self.contradiction_probability, self.missing_evidence_probability
        ) >= 0.5


class MeasurementEvidence(BaseModel):
    model_config = ConfigDict(extra="forbid", allow_inf_nan=False)

    id: str = Field(min_length=1, max_length=100)
    description: str = Field(min_length=1, max_length=1000)
    value: float | int | bool | str
    unit: str | None = Field(default=None, max_length=50)
    quality: Literal["measured", "confirmed", "needs_another_look"]


class RuleEvidence(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=100)
    citation: str = Field(min_length=1, max_length=500)
    source_text: str = Field(min_length=1, max_length=10000)
    human_verified: bool


class ReportClaim(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=100)
    text: str = Field(min_length=1, max_length=2000)
    measurements: list[MeasurementEvidence] = Field(max_length=100)
    cited_rules: list[RuleEvidence] = Field(max_length=100)


@dataclass(frozen=True)
class ClaimVerification:
    claim: ReportClaim
    measurement_support: float
    rule_support: float
    citation_match: float
    supported: bool


@dataclass(frozen=True)
class TextGuardResult:
    overstatement_probability: float
    legal_guarantee_probability: float

    @property
    def allowed(self) -> bool:
        return max(
            self.overstatement_probability, self.legal_guarantee_probability
        ) < 0.5


@dataclass(frozen=True)
class OwnerGoal:
    source_text: str
    kind: GoalKind
    target: str | None
    quantity: int | None
    confidence: float


@dataclass(frozen=True)
class FailureCluster:
    pattern: str
    case_ids: tuple[str, ...]
    mean_probability: float


@dataclass(frozen=True)
class DownstreamGuardResult:
    unsupported_claim_probability: float
    unsafe_recommendation_probability: float
    bad_tool_call_probability: float
    deterministic_tool_violation: bool
    route: ReviewRoute

    @property
    def allowed(self) -> bool:
        return (
            self.route == "automatic"
            and not self.deterministic_tool_violation
            and max(
                self.unsupported_claim_probability,
                self.unsafe_recommendation_probability,
                self.bad_tool_call_probability,
            ) < 0.5
        )


class ConfidenceThresholds(BaseModel):
    """Calibrated per deployment and consequence, not a universal constant."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    reasoning_model_min: float = Field(ge=0.0, le=1.0)
    automatic_min: float = Field(ge=0.0, le=1.0)

    def model_post_init(self, __context, /) -> None:
        if self.reasoning_model_min > self.automatic_min:
            raise ValueError("reasoning_model_min cannot exceed automatic_min")


class RegulationCandidate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=100)
    citation: str = Field(min_length=1, max_length=500)
    text: str = Field(min_length=1, max_length=10000)
    source_kind: Literal["regulation", "case", "guidance"]


@dataclass(frozen=True)
class RankedRegulation:
    candidate: RegulationCandidate
    relevance: ScoreJudgment


@dataclass(frozen=True)
class SemanticFeatures:
    probabilities: dict[str, float]

    def present(self, threshold: float = 0.5) -> tuple[str, ...]:
        if not 0.0 <= threshold <= 1.0:
            raise ValueError("threshold must be between zero and one")
        return tuple(
            feature
            for feature, probability in self.probabilities.items()
            if probability >= threshold
        )
